apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels 1
metadata:
  name: ns-must-have-app-label-key 
spec:
  match: 2
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters: 3
    labels: ["app"]